# --- WIKIS ---
# 1: https://wiki.eventalerts.gg/EventAlertsIntegration/configuration
# 2: https://github.com/srnyx/annoying-api/wiki/File-objects



# API keys for Event Alerts' APIs
# You can set one OR both!
#
# WARNING: Do not, under ANY circumstances, share these API keys with ANYONE, no matter WHAT they say!
# Event Alerts staff will NEVER ask for your API keys.
# We recommend keeping your server files private if you choose to put your API keys here.
# If you think your key was leaked, regenerate it IMEMDIATELY using the appropriate command in Event Alerts' Discord server!
api-keys:

  # This will "connect" your Minecraft server to your Player account, effectively marking this Minecraft server as "your Minecraft server"
  # Run the `/playerapikey` command in Event Alerts' Discord server to get your API key
  player: "PLAYER_API_KEY_HERE"

  # This will "connect" your Minecraft server to your Partner Server, effectively marking this Minecraft as "your Partner Server's Minecraft server"
  # Run the `/server apikey` command in Event Alerts' Discord server to get your server's API key
  server: "SERVER_API_KEY_HERE"



# Settings related to syncing messages from Event Alerts' Discord server to the Minecraft in-game chat
# Requires API key(s) to be set up (see above)
discord-message-syncing:

  # Whether to send messages sent in Event Alerts threads to the Minecraft in-game chat
  enabled: true

  # The format of Discord messages in the Minecraft in-game chat
  # Available placeholders:
  #   - event: <event_id>, <event_type>, <event_channel>, <event_message>, <event_control_panel>, <event_custom>, <event_created>, <event_title>, <event_host>, <event_description>, <event_roles>, <event_roles_named>, <event_server>, <event_media_name>, <event_ip>, <event_platform>, <event_version>, <event_prize>, <event_max_players>, <event_time>, <event_subscribers>
  #  - channel: <channel_id>, <channel_name>
  #  - author: <author_id>, <author_name>, <author_effectivename>
  #  - content: <content_raw>, <content_display>, <content_stripped>
  #  - other: <messageid>, <player_name>
  #  - Any PlaceholderAPI placeholder (%placeholder%)
  format: "<dark_aqua>🎉 [<event_title>] <aqua>[<author_name>] <content_stripped>"



# Settings related to Event Alerts' Minecraft-Discord linking system
linking:

  # Whether to force players to be linked with Event Alerts to join/stay on the server
  # To bypass the requirement, give the player the eventalerts.linking.bypass permission
  require-link: false

  # Whether to check link status when a player joins the server
  check-on-join: true

  # Whether to allow players to join the server when the linking check fails
  allow-join-on-failure: false



# Settings related to Event Alerts' cross-banning feature
cross-ban:

  # Whether to enable cross-ban checking
  # Anyone with eventalerts.crossban.bypass will be exempt from cross-bans
  enabled: true

  # Whether to check cross-ban status when a player joins the server
  check-on-join: true

  # Whether to allow players to join the server when the cross-ban check fails
  allow-join-on-failure: false



# Settings related to Event Alerts' event messages being broadcast in-game
event-messages:

  # Whether to enable event messages being broadcast in the server chat
  enabled: false

  # 1.20.5+
  # If an IP is detected in an event message, players will be able to click a button to join the event's server using transfer packets
  detect-ips: true

  # The sound to play when an event message is broadcasted
  sound: # SOUND (see wiki 2)
    enabled: true
    sound: BLOCK_NOTE_BLOCK_CHIME
    category: AMBIENT

  # Types of events that shouldn't be broadcasted in the server chat
  # Possible values: SKEPPY, POTENTIAL_FAMOUS, SIGHTING, FAMOUS, PARTNER, COMMUNITY
  ignored-types:
    - SIGHTING

  # Ignore Partner events that mention any of these roles
  # Possible values: MONEY, FUN, HOUSING, CIVILIZATION
  ignored-partner-roles:
    - HOUSING
    - CIVILIZATION

  # Ignore Partner/Community events that are posted using any of these formats
  # Possible values: CUSTOM, BUILT
  ignored-formats: []

  # Only broadcast events from these specific hosts
  # You can include both server EA IDs (found in footer of '/server get') and host IDs (Discord user IDs)
  host-filter: []



# Advanced settings that you probably shouldn't touch...
advanced:
  # Whether to enable debug logging
  debug: false
  # Whether to enable using the testing API hosts
  # Only the developer really needs to enable this
  use-testing-api: false
  # Settings for websocket connections
  websockets:
    # Minutes until a websocket attempts to reconnect after being disconnected (min: 3, -1 to disable retries)
    retry-delay: 5
    # Whether to log websocket connection messages
    logs: false
