name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${mainPackage}.${name}
version: ${version}
api-version: 1.18.2

commands:
  eventalerts:
    description: Primary command for Event Alerts
    aliases:
      - ea

permissions:
  eventalerts.reload:
    description: Allows the player to use /eventalerts reload
  eventalerts.config:
    description: Allows the player to use /eventalerts config
  eventalerts.linking.check:
    description: Allows the player to use /eventalerts linking check
  eventalerts.linking.bypass:
    description: Allows the player to bypass the linking requirement
    default: false
  eventalerts.linking.discord:
    description: Allows the player to use /eventalerts linking discord
    default: true
  eventalerts.linking.minecraft:
    description: Allows the player to use /eventalerts linking minecraft
    default: true
  eventalerts.crossban.check:
    description: Allows the player to use /eventalerts crossban check
  eventalerts.crossban.bypass:
    description: Allows the player to bypass the cross-banning system
    default: false
