name: Publish
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  build:
    uses: srnyx/tools/.github/workflows/publish.yml@main
    with:
      modrinth: DmjI2XpF
      java: 21
      versions: ">=1.18.2"
      loaders: |
        purpur
        paper
    secrets: inherit
    permissions:
      contents: write
